### ISSUE TITLE
[openrave] rapidjson not declared when installing on Bionic

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/installation-guides#77] opened 2020-01-10 10:34 UTC
Getting the same error as the one stated in the issue https://github.com/rdiankov/openrave/issues/707 when installing Openrave on Bionic.

Solved it by installing **rapidjson**:

```bash
sudo apt install rapidjson-dev
```

Should we add this line to the installation guide for Bionic?

**Comment by RaulFdzbis** [comment] 2020-01-10 11:30
Possible duplicate of https://github.com/roboticslab-uc3m/installation-guides/issues/65, starting with comments on `rapidjson` at https://github.com/roboticslab-uc3m/installation-guides/issues/65#issuecomment-544455403.

**Comment by jgvictores** [comment] 2020-01-10 15:04
Added at https://github.com/roboticslab-uc3m/installation-guides/commit/8acedc6fe5148450380d55c07e0e32b59047ce41. Closing as duplicate of https://github.com/roboticslab-uc3m/installation-guides/issues/65.

**Closed by jgvictores** 2020-01-10 15:04 UTC
Labels: duplicate, documentation

**Comment by PeterBowman** [comment] 2020-09-09 16:13
Please note current OpenRAVE master branch requires a manual installation of RapidJSON from sources: https://github.com/roboticslab-uc3m/installation-guides/commit/1e61468273a298dec65a2d095024e07cc40bbd29 (https://github.com/roboticslab-uc3m/installation-guides/issues/65#issuecomment-689666111).
